version: '3.4'

services:
      
  profile.api.mysql:
    image: mysql:5.7
    environment:
     MYSQL_RANDOM_ROOT_PASSWORD: 1
     MYSQL_DATABASE: profiledb
     MYSQL_PASSWORD: future
     MYSQL_USER: app
    restart: always
    volumes:
     - dbdata:/var/lib/mysql

  profile.api:
    image: ${DOCKER_REGISTRY-}profileapi
    build:
      context: .
      dockerfile: Profile.Api/Dockerfile
    depends_on:
     - profile.api.mysql

volumes:
    dbdata: