version: '3.4'

services:
  aescryptoapi:
    image: mirzaghulamrasyid.azurecr.io/aescryptoapi:latest
    build:
      context: .
      dockerfile: AESCryptoApi/Dockerfile


  aescryptoweb:
    image: mirzaghulamrasyid.azurecr.io/aescryptoweb:latest
    build:
      context: .
      dockerfile: AESCryptoWeb/Dockerfile
    depends_on:
      - aescryptoapi

